@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package modernmods.modernfoundry.smeltery.block.component;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
