@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package modernmods.modernfoundry.fluids.util;

import modernmods.modernfoundry.compat.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
