@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package modernmods.modernfoundry.smeltery.block.controller;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
