@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package modernmods.modernfoundry.shared.command.argument;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
