@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package modernmods.modernfoundry.fluids;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
